---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  unity-webgl-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/buildstars-online/unity-webgl-nginx.git
    path: kubernetes/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: webgl-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
