apiVersion: v1
kind: Namespace
metadata:
  name: webgl-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgl-nginx
  namespace: webgl-nginx
spec:
  selector:
    matchLabels:
      app: webgl-nginx
  template:
    metadata:
      labels:
        app: webgl-nginx
    spec:
      containers:
      - name: webgl-nginx
        image: deserializeme/unity-webgl-nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webgl-nginx-service
  namespace: webgl-nginx
spec:
  selector:
    app: webgl-nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webgl-nginx-ingress
  namespace: webgl-nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: "https://vouch.buildstars.online/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err"
    nginx.ingress.kubernetes.io/auth-url: https://vouch.buildstars.online/validate
    nginx.ingress.kubernetes.io/auth-response-headers: X-Vouch-User
    nginx.ingress.kubernetes.io/auth-snippet: |
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
spec:
  ingressClassName: nginx
  rules:
  - host: webgl-nginx.buildstars.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webgl-nginx-service
            port:
              number: 8080
