---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgl-nginx
  namespace: webgl-nginx
spec:
  selector:
    matchLabels:
      app: webgl-nginx
  template:
    metadata:
      labels:
        app: webgl-nginx
    spec:
      containers:
      - name: webgl-nginx
        image: deserializeme/unity-webgl-nginx:v0.0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webgl-nginx-service
  namespace: webgl-nginx
spec:
  selector:
    app: webgl-nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webgl-nginx-ingress
  namespace: webgl-nginx
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - webgl-nginx.buildstar.online
      secretName: "webgl-nginx-tls"
  rules:
  - host: webgl-nginx.buildstar.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webgl-nginx-service
            port:
              number: 8080
