name: BuildProject

on: 
  #push: 
  #pull_request:
  workflow_dispatch:
    inputs:
      target_platform:
        description: 'target build platform'
        required: true
        default: 'WebGL'
jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      # Install deps
      - name: Ensure git lfs
        run: sudo apt-get install git-lfs
        shell: bash

      # Fix permissions
      - name: Ensure proper file permissions
        run: |
          ls -hal
          sudo chown $USER:$USER -R unity-webgl-nginx
        shell: bash
        
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
        
      # Test
      #- name: Run tests
      #  uses: game-ci/unity-test-runner@v2
      #  env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #  with:
      #    githubToken: ${{ secrets.GITHUB_TOKEN }}
        
      # Build Unity Project
      # Can fail silently if activation file is invalid which will result 
      # in a completed jib but an empty artifact directory
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
        
      # Upload artifact to storage
      - uses: actions/upload-artifact@v2
        with:
          name: WebGL
          path: build/WebGL
          
      # Copy artifact to docker build context
      - name: move artifact to context
        run: |
          cp -r ./build/WebGL ./docker/
          ls -hal ./docker
          
      # Build Docker Image
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: deserializeme/unity-webgl-nginx
          tags: latest
        
      # Login to Dockerhub
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Push docker image
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
