name: Build Unity Artifact

on: 
  #push: 
  #pull_request:
  workflow_dispatch:
    inputs:
      target_platform:
        description: 'target build platform'
        required: true
        default: 'WebGL'
      custom_image:
        description: 'Custom image name'
        required: true
        default: '2022.1.23f1'
jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      # Install deps
      - name: Ensure git lfs
        run: sudo apt-get install git-lfs
        shell: bash

      # Fix permissions
      - name: Ensure proper file permissions
        run: |
          ls -hal
          sudo chown $USER:$USER -R ../unity-webgl-nginx
        shell: bash
        
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
        
      # Test
      #- name: Run tests
      #  uses: game-ci/unity-test-runner@v2
      #  env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #  with:
      #    githubToken: ${{ secrets.GITHUB_TOKEN }}
        
      # Build Unity Project
      # Can fail silently if activation file is invalid which will result 
      # in a completed jib but an empty artifact directory
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          customImage: 'unityci/editor:2020.1.14f1-base-0'
        
      # Upload artifact to storage
      - uses: actions/upload-artifact@v2
        with:
          name: WebGL
          path: build/WebGL
