name: Cloud Runner

on: 
  #push: 
  #pull_request:
  workflow_dispatch:
    inputs:
      target_platform:
        description: 'target build platform'
        required: true
        default: 'WebGL'
env:
  CLOUD_RUNNER_BRANCH: ${{ github.ref }}
  CLOUD_RUNNER_DEBUG: true
  CLOUD_RUNNER_DEBUG_TREE: true
  DEBUG: true
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: [self-hosted]
    strategy:
      fail-fast: false
      matrix:
        targetPlatform: 
          - "${{github.event.inputs.target_platform}}"
    steps:
      - uses: game-ci/unity-builder@cloud-runner-develop
        id: k8s-unity-build
        with:
          providerStrategy: k8s
          versioning: None
          projectPath: .
          unityVersion: 2021.3.18f1
          targetPlatform: ${{ matrix.targetPlatform }}
          gitPrivateToken: ${{ secrets.GITHUB_TOKEN }}
          # You may want to export your builds somewhere external so you can access it:
          containerHookFiles: aws-s3-upload-build
        env:
          AWS_S3_BUCKET: artifacts
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_S3_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: http://85.10.207.26:32000
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        
      # Upload artifact to storage
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
