name: Cloud Runner

on: 
  #push: 
  #pull_request:
  workflow_dispatch:
    inputs:
      target_platform:
        description: 'target build platform'
        required: true
        default: 'WebGL'
jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform: 
          - "${{github.event.inputs.target_platform}}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: install kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBECONFIG }} | base64 --decode > ${HOME}/.kube/config
          
      - name: Select Context
        run: kubectl config use-context default
      
      - name: Test k8s
        run: kubectl get nodes -A
          
      - uses: game-ci/unity-builder@cloud-runner-develop
        id: k8s-unity-build
        with:
          providerStrategy: k8s
          versioning: None
          projectPath: .
          unityVersion: 2021.3.18f1
          targetPlatform: ${{ matrix.targetPlatform }}
          gitPrivateToken: ${{ secrets.GITHUB_TOKEN }}
          kubeConfig: ${{ secrets.KUBECONFIG }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          AWS_S3_BUCKET: artifacts
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_S3_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: http://85.10.207.26:32000
    
          
        
